### ISSUE TITLE
Has this project been discontinued?

### ISSUE THREAD

**Issue by Vzhangs** [heiyang22/chat#4]

**Comment by heiyang22** [comment]
no，Because of certain uncertainties，this project will restart in 2025

**Comment by Vzhangs** [comment]
Can I get some details? Maybe i can offer assistance.

**Comment by heiyang22** [comment]
ok,Because Bilibili has increased the price of the Grand Voyage membership，I don't have money to recharge my membership for Yongchu Tafei，so i should spend much time to do hard work and I don't have time to develop this project anymore

**Comment by Vzhangs** [comment]
Frustrated. I'm afraid I can't help you with that

**Comment by heiyang22** [comment]
do you like Yongchu Tafei?

**Comment by Vzhangs** [comment]
Sure, but I like pekora better

**Comment by Vzhangs** [comment]
Don't forget Aqua. She's amazing

**Comment by heiyang22** [comment]
Do you have enough money for them to become members？

**Comment by Vzhangs** [comment]
no, I just watched lives in silence

**Comment by heiyang22** [comment]
Why don't you want to deposit money for them! Anyone who doesn't deposit money for VTubers will die!👿👿👿

**Comment by Vzhangs** [comment]
That's because I only make 14.5K a month😭😭

**Comment by heiyang22** [comment]
Kill!😡

**Comment by Vzhangs** [comment]
ji!
